from alembic import op
import sqlalchemy as sa



"""index changes

Revision ID: 01dd02a71732
Revises: f97edbfc1b80
Create Date: 2017-10-03 14:22:30.176602

"""

# revision identifiers, used by Alembic.
revision = '01dd02a71732'
down_revision = 'f97edbfc1b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_message_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('index_message_chat_user_id', 'messages', ['chat_user_id'], unique=False)
    op.drop_index('index_message_uid', table_name='messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_message_uid', 'messages', ['backend_uid'], unique=False)
    op.drop_index('index_message_chat_user_id', table_name='messages')
    op.drop_index('index_message_chat_id', table_name='messages')
    # ### end Alembic commands ###
