from alembic import op
import sqlalchemy as sa



"""initial

Revision ID: 62dc90f35948
Revises: 
Create Date: 2017-10-02 00:32:30.418639

"""

# revision identifiers, used by Alembic.
revision = '62dc90f35948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
