import os
from alembic import op
import sqlalchemy as sa



"""backend type

Revision ID: f97edbfc1b80
Revises: bf33ede69739
Create Date: 2017-10-02 05:43:23.179357

"""

# revision identifiers, used by Alembic.
revision = 'f97edbfc1b80'
down_revision = 'bf33ede69739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('backend_type', sa.Enum('imessage', 'discord', 'skype', name='backendtype')))
    if 'ALEMBIC_DANGER' in os.environ:
        op.execute("UPDATE messages SET backend_type='imessage'")
    op.alter_column('messages', 'backend_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'backend_type')
    # ### end Alembic commands ###
