export const RECIEVE_CHATS = 'RECIEVE_CHATS';
export const UPDATE_CHAT_DATA = 'UPDATE_CHAT_DATA';
export const RECIEVE_MESSAGES = 'RECIEVE_MESSAGES';

export const SET_META = 'SET_META';

export const RECIEVE_CHAT_USERS = 'RECIEVE_CHAT_USERS';
